# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kajames/Dropbox/double_auction

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kajames/Dropbox/double_auction

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kajames/Dropbox/double_auction/CMakeFiles /home/kajames/Dropbox/double_auction/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kajames/Dropbox/double_auction/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

sample_client.o: sample_client.cc.o

.PHONY : sample_client.o

# target to build an object file
sample_client.cc.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/sample_client.cc.o
.PHONY : sample_client.cc.o

sample_client.i: sample_client.cc.i

.PHONY : sample_client.i

# target to preprocess a source file
sample_client.cc.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/sample_client.cc.i
.PHONY : sample_client.cc.i

sample_client.s: sample_client.cc.s

.PHONY : sample_client.s

# target to generate assembly for a file
sample_client.cc.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/sample_client.cc.s
.PHONY : sample_client.cc.s

sample_experiment.o: sample_experiment.cc.o

.PHONY : sample_experiment.o

# target to build an object file
sample_experiment.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/sample_experiment.cc.o
.PHONY : sample_experiment.cc.o

sample_experiment.i: sample_experiment.cc.i

.PHONY : sample_experiment.i

# target to preprocess a source file
sample_experiment.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/sample_experiment.cc.i
.PHONY : sample_experiment.cc.i

sample_experiment.s: sample_experiment.cc.s

.PHONY : sample_experiment.s

# target to generate assembly for a file
sample_experiment.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/sample_experiment.cc.s
.PHONY : sample_experiment.cc.s

src/client/command_line_outputter.o: src/client/command_line_outputter.cc.o

.PHONY : src/client/command_line_outputter.o

# target to build an object file
src/client/command_line_outputter.cc.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/command_line_outputter.cc.o
.PHONY : src/client/command_line_outputter.cc.o

src/client/command_line_outputter.i: src/client/command_line_outputter.cc.i

.PHONY : src/client/command_line_outputter.i

# target to preprocess a source file
src/client/command_line_outputter.cc.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/command_line_outputter.cc.i
.PHONY : src/client/command_line_outputter.cc.i

src/client/command_line_outputter.s: src/client/command_line_outputter.cc.s

.PHONY : src/client/command_line_outputter.s

# target to generate assembly for a file
src/client/command_line_outputter.cc.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/command_line_outputter.cc.s
.PHONY : src/client/command_line_outputter.cc.s

src/client/state.o: src/client/state.cc.o

.PHONY : src/client/state.o

# target to build an object file
src/client/state.cc.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/state.cc.o
.PHONY : src/client/state.cc.o

src/client/state.i: src/client/state.cc.i

.PHONY : src/client/state.i

# target to preprocess a source file
src/client/state.cc.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/state.cc.i
.PHONY : src/client/state.cc.i

src/client/state.s: src/client/state.cc.s

.PHONY : src/client/state.s

# target to generate assembly for a file
src/client/state.cc.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/state.cc.s
.PHONY : src/client/state.cc.s

src/comms/connection.o: src/comms/connection.cc.o

.PHONY : src/comms/connection.o

# target to build an object file
src/comms/connection.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/comms/connection.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/comms/connection.cc.o
.PHONY : src/comms/connection.cc.o

src/comms/connection.i: src/comms/connection.cc.i

.PHONY : src/comms/connection.i

# target to preprocess a source file
src/comms/connection.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/comms/connection.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/comms/connection.cc.i
.PHONY : src/comms/connection.cc.i

src/comms/connection.s: src/comms/connection.cc.s

.PHONY : src/comms/connection.s

# target to generate assembly for a file
src/comms/connection.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/comms/connection.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/comms/connection.cc.s
.PHONY : src/comms/connection.cc.s

src/comms/connection_manager.o: src/comms/connection_manager.cc.o

.PHONY : src/comms/connection_manager.o

# target to build an object file
src/comms/connection_manager.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/comms/connection_manager.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/comms/connection_manager.cc.o
.PHONY : src/comms/connection_manager.cc.o

src/comms/connection_manager.i: src/comms/connection_manager.cc.i

.PHONY : src/comms/connection_manager.i

# target to preprocess a source file
src/comms/connection_manager.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/comms/connection_manager.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/comms/connection_manager.cc.i
.PHONY : src/comms/connection_manager.cc.i

src/comms/connection_manager.s: src/comms/connection_manager.cc.s

.PHONY : src/comms/connection_manager.s

# target to generate assembly for a file
src/comms/connection_manager.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/comms/connection_manager.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/comms/connection_manager.cc.s
.PHONY : src/comms/connection_manager.cc.s

src/comms/message.o: src/comms/message.cc.o

.PHONY : src/comms/message.o

# target to build an object file
src/comms/message.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/comms/message.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/comms/message.cc.o
.PHONY : src/comms/message.cc.o

src/comms/message.i: src/comms/message.cc.i

.PHONY : src/comms/message.i

# target to preprocess a source file
src/comms/message.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/comms/message.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/comms/message.cc.i
.PHONY : src/comms/message.cc.i

src/comms/message.s: src/comms/message.cc.s

.PHONY : src/comms/message.s

# target to generate assembly for a file
src/comms/message.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/comms/message.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/comms/message.cc.s
.PHONY : src/comms/message.cc.s

src/comms/reconnector.o: src/comms/reconnector.cc.o

.PHONY : src/comms/reconnector.o

# target to build an object file
src/comms/reconnector.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/comms/reconnector.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/comms/reconnector.cc.o
.PHONY : src/comms/reconnector.cc.o

src/comms/reconnector.i: src/comms/reconnector.cc.i

.PHONY : src/comms/reconnector.i

# target to preprocess a source file
src/comms/reconnector.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/comms/reconnector.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/comms/reconnector.cc.i
.PHONY : src/comms/reconnector.cc.i

src/comms/reconnector.s: src/comms/reconnector.cc.s

.PHONY : src/comms/reconnector.s

# target to generate assembly for a file
src/comms/reconnector.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/comms/reconnector.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/comms/reconnector.cc.s
.PHONY : src/comms/reconnector.cc.s

src/experiment/controller.o: src/experiment/controller.cc.o

.PHONY : src/experiment/controller.o

# target to build an object file
src/experiment/controller.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/controller.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/controller.cc.o
.PHONY : src/experiment/controller.cc.o

src/experiment/controller.i: src/experiment/controller.cc.i

.PHONY : src/experiment/controller.i

# target to preprocess a source file
src/experiment/controller.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/controller.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/controller.cc.i
.PHONY : src/experiment/controller.cc.i

src/experiment/controller.s: src/experiment/controller.cc.s

.PHONY : src/experiment/controller.s

# target to generate assembly for a file
src/experiment/controller.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/controller.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/controller.cc.s
.PHONY : src/experiment/controller.cc.s

src/experiment/controller_state.o: src/experiment/controller_state.cc.o

.PHONY : src/experiment/controller_state.o

# target to build an object file
src/experiment/controller_state.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/controller_state.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/controller_state.cc.o
.PHONY : src/experiment/controller_state.cc.o

src/experiment/controller_state.i: src/experiment/controller_state.cc.i

.PHONY : src/experiment/controller_state.i

# target to preprocess a source file
src/experiment/controller_state.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/controller_state.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/controller_state.cc.i
.PHONY : src/experiment/controller_state.cc.i

src/experiment/controller_state.s: src/experiment/controller_state.cc.s

.PHONY : src/experiment/controller_state.s

# target to generate assembly for a file
src/experiment/controller_state.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/controller_state.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/controller_state.cc.s
.PHONY : src/experiment/controller_state.cc.s

src/experiment/experiment.o: src/experiment/experiment.cc.o

.PHONY : src/experiment/experiment.o

# target to build an object file
src/experiment/experiment.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/experiment.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/experiment.cc.o
.PHONY : src/experiment/experiment.cc.o

src/experiment/experiment.i: src/experiment/experiment.cc.i

.PHONY : src/experiment/experiment.i

# target to preprocess a source file
src/experiment/experiment.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/experiment.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/experiment.cc.i
.PHONY : src/experiment/experiment.cc.i

src/experiment/experiment.s: src/experiment/experiment.cc.s

.PHONY : src/experiment/experiment.s

# target to generate assembly for a file
src/experiment/experiment.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/experiment.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/experiment.cc.s
.PHONY : src/experiment/experiment.cc.s

src/experiment/experiment_enums.o: src/experiment/experiment_enums.cc.o

.PHONY : src/experiment/experiment_enums.o

# target to build an object file
src/experiment/experiment_enums.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/experiment_enums.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/experiment_enums.cc.o
.PHONY : src/experiment/experiment_enums.cc.o

src/experiment/experiment_enums.i: src/experiment/experiment_enums.cc.i

.PHONY : src/experiment/experiment_enums.i

# target to preprocess a source file
src/experiment/experiment_enums.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/experiment_enums.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/experiment_enums.cc.i
.PHONY : src/experiment/experiment_enums.cc.i

src/experiment/experiment_enums.s: src/experiment/experiment_enums.cc.s

.PHONY : src/experiment/experiment_enums.s

# target to generate assembly for a file
src/experiment/experiment_enums.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/experiment_enums.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/experiment_enums.cc.s
.PHONY : src/experiment/experiment_enums.cc.s

src/experiment/experiment_state.o: src/experiment/experiment_state.cc.o

.PHONY : src/experiment/experiment_state.o

# target to build an object file
src/experiment/experiment_state.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/experiment_state.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/experiment_state.cc.o
.PHONY : src/experiment/experiment_state.cc.o

src/experiment/experiment_state.i: src/experiment/experiment_state.cc.i

.PHONY : src/experiment/experiment_state.i

# target to preprocess a source file
src/experiment/experiment_state.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/experiment_state.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/experiment_state.cc.i
.PHONY : src/experiment/experiment_state.cc.i

src/experiment/experiment_state.s: src/experiment/experiment_state.cc.s

.PHONY : src/experiment/experiment_state.s

# target to generate assembly for a file
src/experiment/experiment_state.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/experiment_state.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/experiment_state.cc.s
.PHONY : src/experiment/experiment_state.cc.s

src/experiment/payout.o: src/experiment/payout.cc.o

.PHONY : src/experiment/payout.o

# target to build an object file
src/experiment/payout.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/payout.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/payout.cc.o
.PHONY : src/experiment/payout.cc.o

src/experiment/payout.i: src/experiment/payout.cc.i

.PHONY : src/experiment/payout.i

# target to preprocess a source file
src/experiment/payout.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/payout.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/payout.cc.i
.PHONY : src/experiment/payout.cc.i

src/experiment/payout.s: src/experiment/payout.cc.s

.PHONY : src/experiment/payout.s

# target to generate assembly for a file
src/experiment/payout.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/experiment/payout.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/experiment/payout.cc.s
.PHONY : src/experiment/payout.cc.s

src/market/ask.o: src/market/ask.cc.o

.PHONY : src/market/ask.o

# target to build an object file
src/market/ask.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/ask.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/ask.cc.o
.PHONY : src/market/ask.cc.o

src/market/ask.i: src/market/ask.cc.i

.PHONY : src/market/ask.i

# target to preprocess a source file
src/market/ask.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/ask.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/ask.cc.i
.PHONY : src/market/ask.cc.i

src/market/ask.s: src/market/ask.cc.s

.PHONY : src/market/ask.s

# target to generate assembly for a file
src/market/ask.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/ask.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/ask.cc.s
.PHONY : src/market/ask.cc.s

src/market/bid.o: src/market/bid.cc.o

.PHONY : src/market/bid.o

# target to build an object file
src/market/bid.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/bid.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/bid.cc.o
.PHONY : src/market/bid.cc.o

src/market/bid.i: src/market/bid.cc.i

.PHONY : src/market/bid.i

# target to preprocess a source file
src/market/bid.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/bid.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/bid.cc.i
.PHONY : src/market/bid.cc.i

src/market/bid.s: src/market/bid.cc.s

.PHONY : src/market/bid.s

# target to generate assembly for a file
src/market/bid.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/bid.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/bid.cc.s
.PHONY : src/market/bid.cc.s

src/market/clearing_queue.o: src/market/clearing_queue.cc.o

.PHONY : src/market/clearing_queue.o

# target to build an object file
src/market/clearing_queue.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/clearing_queue.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/clearing_queue.cc.o
.PHONY : src/market/clearing_queue.cc.o

src/market/clearing_queue.i: src/market/clearing_queue.cc.i

.PHONY : src/market/clearing_queue.i

# target to preprocess a source file
src/market/clearing_queue.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/clearing_queue.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/clearing_queue.cc.i
.PHONY : src/market/clearing_queue.cc.i

src/market/clearing_queue.s: src/market/clearing_queue.cc.s

.PHONY : src/market/clearing_queue.s

# target to generate assembly for a file
src/market/clearing_queue.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/clearing_queue.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/clearing_queue.cc.s
.PHONY : src/market/clearing_queue.cc.s

src/market/holdings.o: src/market/holdings.cc.o

.PHONY : src/market/holdings.o

# target to build an object file
src/market/holdings.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/holdings.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/holdings.cc.o
.PHONY : src/market/holdings.cc.o

src/market/holdings.i: src/market/holdings.cc.i

.PHONY : src/market/holdings.i

# target to preprocess a source file
src/market/holdings.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/holdings.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/holdings.cc.i
.PHONY : src/market/holdings.cc.i

src/market/holdings.s: src/market/holdings.cc.s

.PHONY : src/market/holdings.s

# target to generate assembly for a file
src/market/holdings.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/holdings.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/holdings.cc.s
.PHONY : src/market/holdings.cc.s

src/market/market.o: src/market/market.cc.o

.PHONY : src/market/market.o

# target to build an object file
src/market/market.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/market.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/market.cc.o
.PHONY : src/market/market.cc.o

src/market/market.i: src/market/market.cc.i

.PHONY : src/market/market.i

# target to preprocess a source file
src/market/market.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/market.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/market.cc.i
.PHONY : src/market/market.cc.i

src/market/market.s: src/market/market.cc.s

.PHONY : src/market/market.s

# target to generate assembly for a file
src/market/market.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/market.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/market.cc.s
.PHONY : src/market/market.cc.s

src/market/market_state.o: src/market/market_state.cc.o

.PHONY : src/market/market_state.o

# target to build an object file
src/market/market_state.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/market_state.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/market_state.cc.o
.PHONY : src/market/market_state.cc.o

src/market/market_state.i: src/market/market_state.cc.i

.PHONY : src/market/market_state.i

# target to preprocess a source file
src/market/market_state.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/market_state.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/market_state.cc.i
.PHONY : src/market/market_state.cc.i

src/market/market_state.s: src/market/market_state.cc.s

.PHONY : src/market/market_state.s

# target to generate assembly for a file
src/market/market_state.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/market_state.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/market_state.cc.s
.PHONY : src/market/market_state.cc.s

src/market/offer_validity.o: src/market/offer_validity.cc.o

.PHONY : src/market/offer_validity.o

# target to build an object file
src/market/offer_validity.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/offer_validity.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/offer_validity.cc.o
.PHONY : src/market/offer_validity.cc.o

src/market/offer_validity.i: src/market/offer_validity.cc.i

.PHONY : src/market/offer_validity.i

# target to preprocess a source file
src/market/offer_validity.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/offer_validity.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/offer_validity.cc.i
.PHONY : src/market/offer_validity.cc.i

src/market/offer_validity.s: src/market/offer_validity.cc.s

.PHONY : src/market/offer_validity.s

# target to generate assembly for a file
src/market/offer_validity.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/offer_validity.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/offer_validity.cc.s
.PHONY : src/market/offer_validity.cc.s

src/market/transaction.o: src/market/transaction.cc.o

.PHONY : src/market/transaction.o

# target to build an object file
src/market/transaction.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/transaction.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/transaction.cc.o
.PHONY : src/market/transaction.cc.o

src/market/transaction.i: src/market/transaction.cc.i

.PHONY : src/market/transaction.i

# target to preprocess a source file
src/market/transaction.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/transaction.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/transaction.cc.i
.PHONY : src/market/transaction.cc.i

src/market/transaction.s: src/market/transaction.cc.s

.PHONY : src/market/transaction.s

# target to generate assembly for a file
src/market/transaction.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/market/transaction.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/market/transaction.cc.s
.PHONY : src/market/transaction.cc.s

src/server/client_message_processor.o: src/server/client_message_processor.cc.o

.PHONY : src/server/client_message_processor.o

# target to build an object file
src/server/client_message_processor.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/client_message_processor.cc.o
.PHONY : src/server/client_message_processor.cc.o

src/server/client_message_processor.i: src/server/client_message_processor.cc.i

.PHONY : src/server/client_message_processor.i

# target to preprocess a source file
src/server/client_message_processor.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/client_message_processor.cc.i
.PHONY : src/server/client_message_processor.cc.i

src/server/client_message_processor.s: src/server/client_message_processor.cc.s

.PHONY : src/server/client_message_processor.s

# target to generate assembly for a file
src/server/client_message_processor.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/client_message_processor.cc.s
.PHONY : src/server/client_message_processor.cc.s

src/server/logger.o: src/server/logger.cc.o

.PHONY : src/server/logger.o

# target to build an object file
src/server/logger.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/logger.cc.o
.PHONY : src/server/logger.cc.o

src/server/logger.i: src/server/logger.cc.i

.PHONY : src/server/logger.i

# target to preprocess a source file
src/server/logger.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/logger.cc.i
.PHONY : src/server/logger.cc.i

src/server/logger.s: src/server/logger.cc.s

.PHONY : src/server/logger.s

# target to generate assembly for a file
src/server/logger.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/logger.cc.s
.PHONY : src/server/logger.cc.s

src/server/message_sender.o: src/server/message_sender.cc.o

.PHONY : src/server/message_sender.o

# target to build an object file
src/server/message_sender.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/message_sender.cc.o
.PHONY : src/server/message_sender.cc.o

src/server/message_sender.i: src/server/message_sender.cc.i

.PHONY : src/server/message_sender.i

# target to preprocess a source file
src/server/message_sender.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/message_sender.cc.i
.PHONY : src/server/message_sender.cc.i

src/server/message_sender.s: src/server/message_sender.cc.s

.PHONY : src/server/message_sender.s

# target to generate assembly for a file
src/server/message_sender.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/message_sender.cc.s
.PHONY : src/server/message_sender.cc.s

src/server/outputter.o: src/server/outputter.cc.o

.PHONY : src/server/outputter.o

# target to build an object file
src/server/outputter.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/outputter.cc.o
.PHONY : src/server/outputter.cc.o

src/server/outputter.i: src/server/outputter.cc.i

.PHONY : src/server/outputter.i

# target to preprocess a source file
src/server/outputter.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/outputter.cc.i
.PHONY : src/server/outputter.cc.i

src/server/outputter.s: src/server/outputter.cc.s

.PHONY : src/server/outputter.s

# target to generate assembly for a file
src/server/outputter.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/outputter.cc.s
.PHONY : src/server/outputter.cc.s

src/tools/pausable_timer.o: src/tools/pausable_timer.cc.o

.PHONY : src/tools/pausable_timer.o

# target to build an object file
src/tools/pausable_timer.cc.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/tools/pausable_timer.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/tools/pausable_timer.cc.o
.PHONY : src/tools/pausable_timer.cc.o

src/tools/pausable_timer.i: src/tools/pausable_timer.cc.i

.PHONY : src/tools/pausable_timer.i

# target to preprocess a source file
src/tools/pausable_timer.cc.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/tools/pausable_timer.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/tools/pausable_timer.cc.i
.PHONY : src/tools/pausable_timer.cc.i

src/tools/pausable_timer.s: src/tools/pausable_timer.cc.s

.PHONY : src/tools/pausable_timer.s

# target to generate assembly for a file
src/tools/pausable_timer.cc.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/tools/pausable_timer.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/tools/pausable_timer.cc.s
.PHONY : src/tools/pausable_timer.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... client"
	@echo "... sample_client.o"
	@echo "... sample_client.i"
	@echo "... sample_client.s"
	@echo "... sample_experiment.o"
	@echo "... sample_experiment.i"
	@echo "... sample_experiment.s"
	@echo "... src/client/command_line_outputter.o"
	@echo "... src/client/command_line_outputter.i"
	@echo "... src/client/command_line_outputter.s"
	@echo "... src/client/state.o"
	@echo "... src/client/state.i"
	@echo "... src/client/state.s"
	@echo "... src/comms/connection.o"
	@echo "... src/comms/connection.i"
	@echo "... src/comms/connection.s"
	@echo "... src/comms/connection_manager.o"
	@echo "... src/comms/connection_manager.i"
	@echo "... src/comms/connection_manager.s"
	@echo "... src/comms/message.o"
	@echo "... src/comms/message.i"
	@echo "... src/comms/message.s"
	@echo "... src/comms/reconnector.o"
	@echo "... src/comms/reconnector.i"
	@echo "... src/comms/reconnector.s"
	@echo "... src/experiment/controller.o"
	@echo "... src/experiment/controller.i"
	@echo "... src/experiment/controller.s"
	@echo "... src/experiment/controller_state.o"
	@echo "... src/experiment/controller_state.i"
	@echo "... src/experiment/controller_state.s"
	@echo "... src/experiment/experiment.o"
	@echo "... src/experiment/experiment.i"
	@echo "... src/experiment/experiment.s"
	@echo "... src/experiment/experiment_enums.o"
	@echo "... src/experiment/experiment_enums.i"
	@echo "... src/experiment/experiment_enums.s"
	@echo "... src/experiment/experiment_state.o"
	@echo "... src/experiment/experiment_state.i"
	@echo "... src/experiment/experiment_state.s"
	@echo "... src/experiment/payout.o"
	@echo "... src/experiment/payout.i"
	@echo "... src/experiment/payout.s"
	@echo "... src/market/ask.o"
	@echo "... src/market/ask.i"
	@echo "... src/market/ask.s"
	@echo "... src/market/bid.o"
	@echo "... src/market/bid.i"
	@echo "... src/market/bid.s"
	@echo "... src/market/clearing_queue.o"
	@echo "... src/market/clearing_queue.i"
	@echo "... src/market/clearing_queue.s"
	@echo "... src/market/holdings.o"
	@echo "... src/market/holdings.i"
	@echo "... src/market/holdings.s"
	@echo "... src/market/market.o"
	@echo "... src/market/market.i"
	@echo "... src/market/market.s"
	@echo "... src/market/market_state.o"
	@echo "... src/market/market_state.i"
	@echo "... src/market/market_state.s"
	@echo "... src/market/offer_validity.o"
	@echo "... src/market/offer_validity.i"
	@echo "... src/market/offer_validity.s"
	@echo "... src/market/transaction.o"
	@echo "... src/market/transaction.i"
	@echo "... src/market/transaction.s"
	@echo "... src/server/client_message_processor.o"
	@echo "... src/server/client_message_processor.i"
	@echo "... src/server/client_message_processor.s"
	@echo "... src/server/logger.o"
	@echo "... src/server/logger.i"
	@echo "... src/server/logger.s"
	@echo "... src/server/message_sender.o"
	@echo "... src/server/message_sender.i"
	@echo "... src/server/message_sender.s"
	@echo "... src/server/outputter.o"
	@echo "... src/server/outputter.i"
	@echo "... src/server/outputter.s"
	@echo "... src/tools/pausable_timer.o"
	@echo "... src/tools/pausable_timer.i"
	@echo "... src/tools/pausable_timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

